# Generated by Django 3.0.7 on 2023-05-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hairstyle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hairstyle.Hairstyle'),
        ),
    ]
