# Generated by Django 3.0.7 on 2023-05-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0002_appointment_hairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hairstyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairstyle.Hairstyle'),
        ),
    ]
