# Generated by Django 3.0.7 on 2023-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0003_auto_20230516_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(default=1, upload_to='hairstyles/'),
            preserve_default=False,
        ),
    ]
