# Generated by Django 3.0.7 on 2023-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0004_hairstyle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='image',
            field=models.URLField(),
        ),
    ]
